defmodule Advent2024.Day08Test do
  use ExUnit.Case

  @example """
  ............
  ........0...
  .....0......
  .......0....
  ....0.......
  ......A.....
  ............
  ............
  ........A...
  .........A..
  ............
  ............
  """

  test "part 1" do
    assert Advent2024.Day08.part_1(@example) == 14
  end

  test "part 2" do
    assert Advent2024.Day08.part_2(@example) == 34
  end
end
